### ISSUE TITLE
什么是@font-face?

### ISSUE THREAD

**Issue by kaneruan** [coollcoder/toolbar#2]
@font-face是css3的一个模块，常用于Logo,tags

``` css
@font-face {
       font-family: <YourWebFontName>;
       src: <source> [<format>][,<source> [<format>]]*;
       [font-weight: <weight>];
       [font-style: <style>];
     }
```
- YourWebFontName:此值指的就是你自定义的字体名称，最好是使用你下载的默认字体（下载回来的叫什么字体，这里就填什么字体名），他将被引用到你的Web元素中的font-family。如“font-family:"YourWebFontName";”
- source:此值指的是你自定义的字体的存放路径，可以是**_相对路径**_也可以是**_绝对路径**_；
